### ISSUE TITLE
Request: Speaker

### ISSUE THREAD

**Issue by Tim3game** [theoriginalbit/MoarPeripherals#15]
Hey, please add speaker that when you write for example "speaker.speak("Hello")" it says Hello. Speaker can be also found in Misc Peripheral. PS: In a Misc. Peripheral, Peripherals++ and others peripheral mods for CC, its using the Google API for the voice of the text.

**Comment by theoriginalbit** [comment]
I am looking into it and it is planned. I will not be using the Google API however. The Google API only has a certain amount of requests before it is no longer free, I don't wish to pay for a service simply for a mod I make in my spare time and make no money off.

**Comment by SoniEx2** [comment]
Misc P. doesn't use Google API, it uses the local system's text-to-speech APIs.

**Comment by theoriginalbit** [comment]
Actually MiscP did have a speech adapter that used the Google TTS API, I'm unaware of when it was actually put to use though.

**Comment by SoniEx2** [comment]
Or maybe it used Google's as a fallback...

**Comment by theoriginalbit** [comment]
I have a feeling it was a fallback adapter.
