### ISSUE TITLE
Iron Note Block improvements

### ISSUE THREAD

**Issue by theoriginalbit** [theoriginalbit/MoarPeripherals#33]
- [ ] Add volume
- [x] Add `pling` and `bass` instruments from Computronics
- [ ] Allow instruments via string
- [x] Allow registering of instruments via MoarP API

SoniEx2/NBSPlayer#2

**Comment by nevercast** [comment]
:+1:

**Comment by SoniEx2** [comment]
Btw you can make todo lists

- [ ] a
- [ ] b
- [x] c

etc

```
- [ ] a
- [ ] b
- [x] c
```

**Comment by theoriginalbit** [comment]
I am aware, but thank you.

**Comment by theoriginalbit** [comment]
Volume and strings are waiting on theoriginalbit/Peripheral-Framework#3 which I should get more of a chance to work on once Uni has finished in two weeks.

**Comment by BombBloke** [comment]
Could I suggest that instead of adding support for extra sounds within MineCraft - sounds which may or may not be present within any given install - you instead give access to whatever MIDI synth is available? That'd provide a TON of sounds, pretty much all of which could be found on most any system! Probably even on those dodgy "Mac" thingies!

**Comment by theoriginalbit** [comment]
well the `pling`and `bass` are vanilla sounds. I have added sound effects [like so](https://github.com/theoriginalbit/MoarPeripherals/blob/1bf80b4777af8614eae88cd6eb102c45ffc98b71/src/main/java/com/theoriginalbit/moarperipherals/common/registry/IronNoteRegistry.java#L34-L63).

I have been considering adding some kind of synth, though it's all about trying to get the one that is built in Java to work well with Minecraft in similar ways to the note (i.e. hearing distance and volume), which is no small feat.

**Comment by SoniEx2** [comment]
@BombBloke doesn't work well with Minecraft.
