### ISSUE TITLE
Default chatbox range should be a configuration setting

### ISSUE THREAD

**Issue by SoniEx2** [theoriginalbit/MoarPeripherals#35]
From #34, emphasis mine:

> Make it so when chatboxes are placed, they use a **specified** range by default. Say the max read range is -1 but the default read range is 16, then the chatbox can only see messages within 16 blocks when placed, but can be adjusted to -1 with setReadRange().

**Comment by theoriginalbit** [comment]
There was no need to make a new issue for this.

**Comment by SoniEx2** [comment]
Sorry, this is just the way I usually do things. Will keep that in mind.

**Comment by theoriginalbit** [comment]
No problems, if its directly related (which in this case it is) you can just reopen the issue. :)

**Comment by SoniEx2** [comment]
Uhh... actually it doesn't give me that option...

**Comment by theoriginalbit** [comment]
Odd. In any case this is done and so is #34
