### ISSUE TITLE
Block/item registration should happen at pre-initialization

### ISSUE THREAD

**Issue by SoniEx2** [theoriginalbit/MoarPeripherals#37]
Currently you register blocks and items at init. This is bad practice. Forge doesn't warn you about it yet but it's still bad practice. (Idk the technical reasons for it, I just know I'm told to do it at pre-init)

**Comment by theoriginalbit** [comment]
I am yet to find evidence of this, but I can make the change easily enough.

**Comment by SoniEx2** [comment]
Oh and recipes (usually) happen at init (unless you depend on another mod's items, then you gotta wait for that mod)

**Comment by theoriginalbit** [comment]
I would love to see your evidence. All the mods I have ever seen the source for would disagree

**Comment by SoniEx2** [comment]
Ok. I don't have any other than "it's what the forge modding tutorials told me!"

**Comment by theoriginalbit** [comment]
I will agree that creating the blocks and items early is probably a good thing, but I fail to see where I initialise my recipes makes any difference to anything, unless I need items from another mod, in which case a post-init makes sure that the mods that create their items in pre-init and init are available to me.
