### ISSUE TITLE
ChatBox improvements

### ISSUE THREAD

**Issue by martin2250** [theoriginalbit/MoarPeripherals#38]
Add a tellraw method to chatboxes

**Comment by theoriginalbit** [comment]
which does?

**Comment by martin2250** [comment]
It should allow to send JSON formatted strings => colorerd text,  hyperlinks, clickable text.  
I'm working on a chat based item requesting system and wanted to send buttons that will again say something in the chat when clicked.   
  
So basically the same thing as the /tellraw command. Though you'd probably need to make it less powerful (or at least add options to do so) so people can still see where the message came from. (the command isn't normally available to non-ops)

**Comment by theoriginalbit** [comment]
Ah you meant like the `tellraw` command.

I will consider this for the Admin ChatBox, however I will not add it to the normal ChatBox because as you stated the `tellraw` command is for Opped players.

**Comment by Selim042** [comment]
What about tellraw - clickable text and + the [Name Tag] at the begining.  So, pretty much formatted text with colors and **bold**, _italics_, <ins>underlining</ins>...

**Comment by theoriginalbit** [comment]
I can allow colors, bold, italics, and underline. However since ComputerCraft doesn't support `\u00a7` which is `§` it means that I will have to use a different prefix. I am thinking a simple `\\f` followed by the code

```
BLACK = 0
DARK_BLUE = 1
DARK_GREEN = 2
DARK_AQUA = 3
DARK_RED = 4
DARK_PURPLE = 5
GOLD = 6
GRAY = 7
DARK_GRAY = 8
BLUE = 9
GREEN = a
AQUA = b
RED = c
LIGHT_PURPLE = d
YELLOW = e
WHITE = f
OBFUSCATED = k
BOLD = l
STRIKETHROUGH = m
UNDERLINE = n
ITALIC = o
RESET = r
```

so for example doing `\\f9\\fnHello formatting` would yield
![the following](https://cloud.githubusercontent.com/assets/1377564/7952081/4e40374c-09f3-11e5-8d8d-e6124bcf2d36.png)

**Comment by Selim042** [comment]
yay!

**Comment by theoriginalbit** [comment]
no links though, not exactly sure how those are done yet.

**Comment by theoriginalbit** [comment]
no links for now.
