### ISSUE TITLE
The Note Program should be able to be used on Turtles

### ISSUE THREAD

**Issue by Selim042** [theoriginalbit/MoarPeripherals#39]
I would LOVE a mobile jukebox to follow me around.

**Comment by theoriginalbit** [comment]
I had brought this up with @BombBloke at one point, but I'm not sure of the reply

**Comment by BombBloke** [comment]
How's a turtle going to follow you around? Even if you write the necessary code to handle the pathfinding (no small task), turtles are slow and can't fit through gaps that player characters can.

Turtles also have tiny displays. Can't say I'm enthusiastic about writing a new interface for them.

That said, Note *does* already work on turtles - as an API, all documented within the script file itself. It's trivial to simply get music playing:

    os.loadAPI("moarp/note")
    
    local myMusic = fs.find("*.nbs")
    
    while true do
      for i = 1, #myMusic do
        print("Now playing: " .. myMusic[i])
        note.playSong(myMusic[i])
      end
    end

If someone wants a fancier interface for turtles, I'd rather they use that API to write one!

**Comment by theoriginalbit** [comment]
> Turtles also have tiny displays. Can't say I'm enthusiastic about writing a new interface for them.

Have you tested to see how well it scales?

**Comment by Selim042** [comment]
[**@BombBloke**](https://github.com/BombBloke) commented on [Jun 5, 2015, 5:38 AM CDT](https://github.com/theoriginalbit/MoarPeripherals/issues/39#issuecomment-109255441 "2015-06-05T10:38:58Z - Replied by Github Comment Enhancer"):
> How's a turtle going to follow you around? Even if you write the necessary code to handle the pathfinding (no small task), turtles are slow and can't fit through gaps that player characters can.

And, I have written code to follow players around in the past.

**Comment by BombBloke** [comment]
> Have you tested to see how well it scales?
The interface scales from a minimum 50x7 display up to pretty much anything. Turtles are 39x13.

**Comment by theoriginalbit** [comment]
> The interface scales from a minimum 50x7 display

What is restricting it to 50?

**Comment by BombBloke** [comment]
Line 411, technically, where it errors out if the display isn't wider.

But that's when display elements from the top toolbar start being pushed off the screen, see. There's the logo, the skip back/play/skip forward buttons (centered), the three different auto-play modes and then the quit button. To fit them in I'd need to define a new toolbar layout, remapping all the "clickable" areas and so on. Fun fun.

Which I guess I'll end up doing. Probably tomorrow.

**Comment by theoriginalbit** [comment]
Ah I see, perhaps you could define them as buttons so they can easily be repositioned.

Also if it's only the toolbar that is restricting Note running on Turtles, perhaps we could detect it's a Turtle and use a toolbar that has less ASCII art, it could literally just say `Note` and have the play as `|>`, pause as `||`, and stop as `[]`. Less height, less width, might be more likely to fit.

**Comment by BombBloke** [comment]
I'll indeed be doing just that. If it were only a matter of moving the elements around, I wouldn't've put in such a restriction in the first place.  :P 

The reason I didn't build a smaller interface to begin with was because I was convinced no one will use it on turtles. And I'm still not - but what the heck, I'll make it support "bluetooth speakers" and have it run on pocket computers. That could be somewhat useful.
