### ISSUE TITLE
Fiery Turtle bug

### ISSUE THREAD

**Issue by martin2250** [theoriginalbit/MoarPeripherals#40]
Hi, I'm getting some really strange behaviour from furnace turtles:
it won't accept smelting a single stack in any inventory slot
![smelt](https://cloud.githubusercontent.com/assets/8293473/7980467/f1ebce38-0aa7-11e5-90ed-9e182096b67c.PNG)

when you fill all slots but one, it behaves strange and destroys one item:
![smelt1](https://cloud.githubusercontent.com/assets/8293473/7980490/44a5d9a2-0aa8-11e5-98e8-0861327af5f4.PNG)
The 3rd item dissapeared when it was clicked

I looked into the [source](https://github.com/theoriginalbit/MoarPeripherals/blob/7f3bcc50a1147d2b015d607647dd30b98e20a116/src/main/java/com/moarperipherals/integration/peripheral/PeripheralFurnace.java) and could not find any obvious errors, although the whole method works in a strange way.  
  
Also I have another suggestion: as the original inventor of the furnace turtle pointed out, the smelt method should also support just one argument >furnace.smelt(slot)< which smelts the entire stack in that slot without the need for an empty slot in the turtle's inventory.

**Comment by theoriginalbit** [comment]
What version are you running?

**Comment by martin2250** [comment]
MoarPeripherals-1.7.10-1.7-1.53

**Comment by theoriginalbit** [comment]
okay thank you for the report, I will take a look into this ASAP.

as for being able to use `furnace.smelt(slot)` without the amount, this feature will be available once I have completed theoriginalbit/Peripheral-Framework#3

**Comment by BombBloke** [comment]
Pretty sure I already told you about this, and that you already fixed it?

https://github.com/theoriginalbit/MoarPeripherals/issues/27

**Comment by theoriginalbit** [comment]
well apparently it's present again. @BombBloke if you'd like to verify the issue for yourself please? I'm yet to actually verify the issue still exists, busy week.

**Comment by BombBloke** [comment]
Ok, tested with 1.53-snapshot-88, all's well. 1.53 "proper" pre-dates the old issue by about a week, so the fix simply never went into a "stable" release.

There's one remaining oddity where, if the turtle's inventory is full, attempting to smelt will throw a "not enough space in inventory" error *even if* the items that would be removed during the process would leave a slot free for the new items.

**Comment by theoriginalbit** [comment]
Oh really? I thought that made it to stable, hmm. Okay so the changelog for this coming update will be huge!

Yeah I am aware of this issue with it making an open slot, I do need to handle that, it was an oversight. I'll leave this issue open until that one is fixed.
