### ISSUE TITLE
Overwriting OpenP command

### ISSUE THREAD

**Issue by Nathan1852** [theoriginalbit/MoarPeripherals#47]
Could it be that the chatbox overwrites the OpenPeripheral glasses command? 
I found this in the log: [Server thread/INFO] [MoarPeripherals/MoarPeripherals]:  [MoarP]: Detected OpenPeripheral-Addons installed. Registering the terminal glasses command as a ChatBox command so it is ignored by ChatBoxes.
And the glasses command doesn't work anymore

**Comment by Selim042** [comment]
Already addressed in OpenMods/OpenPeripheral-Addons#65

**Comment by Selim042** [comment]
Already addressed in OpenMods/OpenPeripheral-Addons#65
