### ISSUE TITLE
Enhanced Interactive sorter

### ISSUE THREAD

**Issue by Nathan1852** [theoriginalbit/MoarPeripherals#48]
I think it would be very usefull if the interactive sorter could wrap inventories next to it, since this would enable someone to make a wall of barrels with interactive sorters behind it, so one could wrap the barrel and find out how much items are in it

**Comment by theoriginalbit** [comment]
it is already possible, there is a [`list` method](https://github.com/theoriginalbit/MoarPeripherals/blob/master/src/main/java/com/moarperipherals/tile/TileInteractiveSorter.java#L100-L117) on the interactive sorter which returns a list of all the items that are on the supplied side.
