### ISSUE TITLE
Chatbox Bugs

### ISSUE THREAD

**Issue by FNCxPro** [theoriginalbit/MoarPeripherals#49]
When using a chatbox, you can say a large string through the chatbox and you will then crash whoever could read the message because it was too big of a string. You could possibly fix this by setting a cap at the amount of characters in the message said through say and tell functions.
What happens when you send it is that it "kicks" you from the server and it will say "Disconnected from server."

**Comment by theoriginalbit** [comment]
Logs?

**Comment by FNCxPro** [comment]
It isn't a crash log, it is only latest.log because the bug doesn't crash clients, it only disconnects them.

**Comment by FNCxPro** [comment]
@theoriginalbit I gave you logs and code to reproduce the major bug.

**Comment by theoriginalbit** [comment]
you don't need to @ notify me all the time, this is my repo I get notified when anything happens to it. I see you gave me the logs, the last few days have been busy for me.

**Comment by FNCxPro** [comment]
My reproduce code was very specific, the base crash string was 4 characters and it was concatentated to itself 20k times, the crash string would be 32768 characters long. That is how many characters I used to crash people.

**Comment by theoriginalbit** [comment]
could never replicate on client or server, suspect it may be a chat mod or something installed having issues with it.
