### ISSUE TITLE
[Domain] Website/Wiki/Downloads unavilable

### ISSUE THREAD

**Issue by spannerman79** [theoriginalbit/MoarPeripherals#52]
I think the title is quite clear......

**Comment by nevercast** [comment]
Looks like @theoriginalbit has let the domain expire.

**Comment by theoriginalbit** [comment]
Indeed. The CurseForge project is still up, and for now Cranium has still left the Jenkins build server up so the more recent builds of things that weren't released will be on there.

**Comment by KnightMiner** [comment]
Is there an alternate place for the wiki, such as are you planning on using the GitHub wiki system?

Also, since this is intended, you might want to edit the OP of the thread on the ComputerCraft forums to point to the CurseForge download rather than the expired domain

**Comment by theoriginalbit** [comment]
Nope, no plans for that. The entire wiki was run off a MediaWiki, so it can't be easily published elsewhere, and the time and effort required to manually put it over to the GitHub wiki is not worth the time.
