### ISSUE TITLE
error in line 120

### ISSUE THREAD

**Issue by xxfoofyxx** [theoriginalbit/MoarPeripherals#56]
everytime i open the script, it closes with the error
note:120: attempt to index ? (a nil value)

**Comment by theoriginalbit** [comment]
I'm going to need some [extra details](https://github.com/theoriginalbit/MoarPeripherals/blob/master/.github/ISSUE_TEMPLATE.md) to help you here. [Line 120 of the note program is a comment](https://github.com/theoriginalbit/MoarPeripherals/blob/master/src/main/resources/assets/moarperipherals/lua/note.lua#L120).

**Comment by BombBloke** [comment]
The report relates to [the version in my pastebin](https://pastebin.com/Zs0JAs1b), which would've tripped up pre-CC1.76. It should be functional back to 1.6 now.
