### ISSUE TITLE
Request: HTML Monitor

### ISSUE THREAD

**Issue by KingofGamesYami** [theoriginalbit/MoarPeripherals#6]
Basically, it would be a block that acts like a normal monitor, but renders a sort of HTML code instead of manually printing everything to it.  Since it is html, the resolution would be higher as well, but it would be difficult to make anything (such as animations) that would cause intense lag.

Sample code:
```lua
local html = peripheral.wrap( "left" )
local frame = [[
<!DOCTYPE html>
<html>
 <a href="event: b1">Button 1</a> --queues an event with parameter b1  All events would  of course be html events
 <a href="lua:os.shutdown()">Shutdown</a> --runs the code os.shutdown() on connected  pc's
 <p style="color:#FF0000FF">MoarColors</p> --lots of colors :)
</html>
]]
html.render( frame )
local event, bpress = os.pullEvent( "html" )
if bpress == "b1" then
print( "Button 1 was pressed on the html peripheral!" )
end
```
I would prefer that this stuff be taken into account, but if you don't add all the suggested stuff, at least allow ```<a href="">``` tags to queue events, as to allow the monitor to be interactive.  You might also add CSS in, if possible.  Instead of actually giving a URL for CSS it would be a local file.  This would be a great peripheral to encourage people to learn html, and there's a lot of stuff you could continue to add to this peripheral, such as php or javascript. 

PS:  Just realized, everything is ```<a>``` or ```<p>``` tags in the example, there would of course be much more than that, such as ```<div>``` and ```<span>```.

**Comment by nevercast** [comment]
WurmOnline had BML markup for it's windowing API.
Perhaps some other markup derived language, be it an XML type or something like YAML. Simple markup for rendering something to a screen would be a very nice addition.

**Comment by theoriginalbit** [comment]
Monitor development has stalled, I've hit limitations of not understanding OpenGL quite as well as I thought. I will get onto it again soon... hopefully.

@nevercast you might also be interested in the new ideas I have for theoriginalbit/Graphics-Library in which it will be a setup similar to that of Android.

**Comment by nevercast** [comment]
Was it too much to put the whole URL there :P

Yes I'm very much interested in this! I'm also interested in getting back in to doing some OPC/OPA/OPI development.

**Comment by theoriginalbit** [comment]
I've been thinking about this a lot lately, I don't think I want to go through the effort of adding any kind of markup language for a monitor.
